### ISSUE TITLE
How use this code for CPSO?

### ISSUE THREAD

**Issue by mhosseini20** [mhasanzadeh/Cooperative-PSO-LA#1]
Thanks much for share this code. But, How use this code for CPSO algorithm (A Cooperative Approach to Particle Swarm Optimization[[1](https://ieeexplore.ieee.org/document/1304845)])?

**Comment by hmofrad** [comment]
You're welcome. Thank you for your interest. Please go to my other repository for Adaptive-CPSO where you can find a "body.m" bootstrap file, e.g., for CEC2005: https://github.com/hmofrad/Adaptive-CPSO/blob/master/CEC2005/body.m

The "body.m" is the entry point to a test suit. What you need to do is to, copy the "cpsoh.m" or "cpsos.h" to a test suite and modify its "body.m" to point to the "cpsoh" or "cpsos" methods . Those methods should work with the test suits reported in the paper. Hope this helps.

**Comment by mhosseini20** [comment]
Thank you so much for your fast and useful help

> You're welcome. Thank you for your interest. Please go to my other repository for Adaptive-CPSO where you can find a "body.m" bootstrap file, e.g., for CEC2005: https://github.com/hmofrad/Adaptive-CPSO/blob/master/CEC2005/body.m
> 
> The "body.m" is the entry point to a test suit. What you need to do is to, copy the "cpsoh.m" or "cpsos.h" to a test suite and modify its "body.m" to point to the "cpsoh" or "cpsos" methods . Those methods should work with the test suits reported in the paper. Hope this helps.
